Solved the 9 & 10 profile page issues
BrightMindEnrichment/StreetCare pull request #111
Opened 2024-10-18 22:33 UTC by virajdoshi11

The profile page did not display the profile picture of the user and the user was not able to edit the profile information. These bugs are fixed in this commit.
The respective issues in the design issues document are 9th and 10th under Profile Page

2024-10-24 05:13 UTC, BrightMindEnrichment requested changes
@virajdoshi11 This PR is from a forked repository decline this PR: I have sent you an invitation to join as a collaborator to this repository accept this invite and create a new branch from visitLog_Dev_v2 which is our base development branch

2024-10-24 05:14 UTC, BrightMindEnrichment commented on settings.gradle
This file should not be edited

2024-10-24 05:14 UTC, BrightMindEnrichment commented on gradlew.bat
This file should not be edited

2024-10-24 05:20 UTC, phillipsk requested changes
What is your environment setup? There are several edits to the gradlew and gradlew.bat files that likely should not be edited. Are you able to clone the repository and run the visitLog_Dev_v2 branch? Did these files require changes with the gradle wrapper upgrade to 8.10.2 ?

2024-10-24 05:20 UTC, phillipsk commented on gradlew.bat
This file should not be edited and committed with the PR

2024-10-24 05:20 UTC, phillipsk commented on gradlew
This file should not be edited and committed with the PR

2024-10-29 21:40 UTC, virajdoshi11 commented
Hi, Kevin. I cloned the `visitLog_Dev_v2` branch however every time I tried to run, it showed an error with this dependency `"com.github.smarteist:Android-Image-Slider:1.4.0"`. After going through the dependency's issues, I found out how to properly define it and that the older version (1.39) which was used before has been deprecated. Hence, this change was made to ensure proper functioning.

2024-11-05 04:58 UTC, phillipsk commented
> Hi, Kevin. I cloned the `visitLog_Dev_v2` branch however every time I tried to run, it showed an error with this dependency `"com.github.smarteist:Android-Image-Slider:1.4.0"`. After going through the dependency's issues, I found out how to properly define it and that the older version (1.39) which was used before has been deprecated. Hence, this change was made to ensure proper functioning.

Many devs can checkout the visitLog_dev_v2 branch and run the code as is with no changes. You have made changes to gradlew file which is not typically especially since other developers can clone, checkout the visitLog_dev_v2 main branch and run the project without errors. I understand you mentioned the import dependency com.smarteist.autoimageslider was causing issues 

Do we need the changes to gradle1 and gradlew.bat ? Why were changes made to this file

2025-05-16 23:05 UTC, closed without merging