Adding verification mark to events and help requests
BrightMindEnrichment/StreetCare pull request #112
Opened 2024-10-24 17:15 UTC by SwathiSelvakumaran

2024-10-25 03:02 UTC, phillipsk requested changes

2024-10-25 03:02 UTC, phillipsk commented on app/src/main/res/layout/fragment_profile_my_events.xml
> +                android:id="@+id/llStatus"
The `llStatus` layout is repeated in each of these 4 layout files. Can you refactor this into a standalone layout file and use the `<include` attribute to import the standalone layout

2024-10-30 21:06 UTC, SwathiSelvakumaran commented on app/src/main/res/layout/bottom_sheet_help_request.xml
> +                        android:layout_height="25dp"
Size adjusted according to the text view size already existing to maintain user view experience.

2024-10-30 21:06 UTC, SwathiSelvakumaran commented on app/src/main/res/layout/bottom_sheet_event.xml
> +                    android:layout_width="wrap_content"
addressed

2024-11-05 04:49 UTC, phillipsk approved these changes

2024-11-05 12:01 UTC, merged