Share-With-Community-Fixture
BrightMindEnrichment/StreetCare pull request #121
Opened 2024-12-21 04:22 UTC by Trilok6132

Added "Share with Community" dialog box on Visit Log page

2024-12-23 22:53 UTC, SwathiSelvakumaran commented on app/build.gradle
Please remove the build.gradle changes and resolve other conflicts

2024-12-23 23:28 UTC, Trilok6132 commented
Hi Swathi, kindly check now

2024-12-27 23:15 UTC, SwathiSelvakumaran requested changes

2024-12-30 23:36 UTC, Trilok6132 commented
Hi @SwathiSelvakumaran, please check now and let me know

2025-01-06 23:23 UTC, SwathiSelvakumaran commented on settings.gradle
> +        flatDir {
line 14 15 and 16 should not be present

2025-01-23 22:54 UTC, SwathiSelvakumaran approved these changes

2025-01-23 22:57 UTC, SwathiSelvakumaran commented on app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
> +            Toast.makeText(context, "Please log in to share info", Toast.LENGTH_SHORT).show()
Check if hard coded strings can be moved to strings and es/strings

2025-01-23 23:20 UTC, phillipsk requested changes

2025-01-23 23:20 UTC, phillipsk commented on app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
> +            Toast.makeText(context, "Please log in to share info", Toast.LENGTH_SHORT).show()
Need this resolved @Trilok6132

2025-01-24 06:18 UTC, Trilok6132 commented on app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
> +            Toast.makeText(context, "Please log in to share info", Toast.LENGTH_SHORT).show()
Hi @phillipsk , @SwathiSelvakumaran ,

I have tried to push my code to the branch but it's creating a lot of merge conflicts with strings.xml file.

2025-01-24 22:55 UTC, SwathiSelvakumaran commented on app/src/main/java/org/brightmindenrichment/street_care/ui/visit/visit_forms/SurveySubmittedFragment.kt
> +            Toast.makeText(context, "Please log in to share info", Toast.LENGTH_SHORT).show()
Try pulling the latest code from the branch and then add your changes

2025-01-24 23:00 UTC, phillipsk approved these changes

2025-01-24 23:04 UTC, merged