Visit log pagination issues
BrightMindEnrichment/StreetCare pull request #80
Opened 2024-08-12 03:14 UTC by SwathiSelvakumaran

last item on the visit log list not being shown fully

![image](https://github.com/user-attachments/assets/5decbfc2-ea0c-4bd2-81fa-b3746b76d3b1)

progress text not shown on some forum questions

![image](https://github.com/user-attachments/assets/266f03be-7be7-4829-aae5-54f2498c279f)

2024-08-13 04:25 UTC, phillipsk commented
I created a new emulator `small phone` and attached a video of the screens which cannot scroll and views are cut off with a small screen size

<img width="689" alt="image" src="https://github.com/user-attachments/assets/0015883b-2117-4814-81ed-3f241b35baf9">


https://github.com/user-attachments/assets/61db190e-2f50-4f14-9f16-490f9c6c1327

2024-08-13 05:17 UTC, phillipsk commented on app/src/main/res/layout/fragment_visit_form3.xml
> +    android:layout_height="match_parent">
nit: fillViewport="true"

2024-08-13 05:21 UTC, phillipsk requested changes
Many of the visit log fragment layouts need the ability to scroll. The most effective way would be to edit each file as you have done with fragment_visit_form3 and fragment_visit_form4

Another consideration would be some sort of abstraction with a new layout file and using an include block as below but this might overcomplicate the task and require 6-7 more layout files. 

<?xml version="1.0" encoding="utf-8"?>
<androidx.core.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true">

    <include
        layout="@layout/fragment_visit_form1" />

</androidx.core.widget.NestedScrollView>

2024-08-13 22:14 UTC, SwathiSelvakumaran commented
Hey Kevin,
Which method would you like to incorporate for all the visit log fragment layouts and do you know which all layout must be incorporated for the changes.

2024-08-13 22:24 UTC, phillipsk commented
You could implement the same approach you have already done with form 3-4
change the all the layouts to be scroll view.

On Tue, Aug 13, 2024 at 6:15 PM Swathi Selvakumaran <
***@***.***> wrote:

> Hey Kevin,
> Which method would you like to incorporate for all the visit log fragment
> layouts and do you know which all layout must be incorporated for the
> changes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BrightMindEnrichment/StreetCare/pull/80#issuecomment-2287232256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZ32OYH3C5YLLXJ3Q2SEC3ZRKAPJAVCNFSM6AAAAABMLKSTEGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDEOBXGIZTEMRVGY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-08-14 21:43 UTC, phillipsk approved these changes
If you want to enhance the performance in a separate PR you could look into replacing the nested LinearLayouts with Constraint layout

https://developer.android.com/develop/ui/views/layout/improving-layouts/optimizing-layouts 

This PR is good to merge as is without this enhancement, that can be reviewed in another task. There are outstanding merge conflicts with fragment_profile.xml

Resolve those and merge this in

2024-08-14 22:12 UTC, merged